stages:
  - check

variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  tags:
    - rust
  before_script:
    - apt-get update -qq && apt-get install -y -qq libdbus-1-dev libasound2-dev libopus-dev pkg-config protobuf-compiler

build:
  stage: check
  script:
    - cargo build --workspace
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  stage: check
  script:
    - cargo test --workspace
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

clippy:
  stage: check
  script:
    - cargo clippy --workspace --all-targets -- -D warnings
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

fmt:
  stage: check
  script:
    - cargo fmt --all -- --check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
