//! Reproducible regeneration of the `[color.*]` blocks in
//! `tokens/design.toml`.
//!
//! Run:
//!
//! ```sh
//! cargo run --example generate_palette -p voicetastic-tokens
//! ```
//!
//! The output goes to stdout — paste the relevant `[color.light]` /
//! `[color.dark]` blocks into `tokens/design.toml` to update the
//! palette. Edit the constants below to change the seed colour or the
//! M3 style.
//!
//! Uses the `material-colors` crate (Rust port of Google's
//! material-color-utilities). Algorithms — hue ring, tonal palette
//! derivation, contrast adjustment — are identical to those that
//! drive Compose `MaterialTheme` on Android, so a desktop palette
//! generated here is wire-compatible with anything generated from
//! the same seed by the MaterialKolor builder.

use material_colors::{
    color::Argb,
    dynamic_color::DynamicScheme,
    hct::Hct,
    scheme::{Scheme, variant::SchemeTonalSpot},
};

/// Seed colour. Match the Android app's MaterialKolor seed
/// (`#FFBDA8`, a warm peach) so the desktop and Android themes share
/// the same brand origin even if their styles differ.
const SEED: u32 = 0xFFFFBDA8;

fn main() {
    let seed = Argb::from_u32(SEED);
    let hct: Hct = seed.into();

    let light = Scheme::from(scheme_for(&hct, false));
    let dark = Scheme::from(scheme_for(&hct, true));

    println!("# Generated by `cargo run --example generate_palette -p voicetastic-tokens`.");
    println!(
        "# Seed: #{:06X}  •  Style: TonalSpot  •  Spec: SPEC_2025",
        SEED & 0x00FFFFFF
    );
    println!();
    print_color_scheme("light", &light);
    println!();
    print_color_scheme("dark", &dark);
    println!();
    print_fixed_colors(&light); // Fixed roles are mode-independent.
}

fn scheme_for(hct: &Hct, is_dark: bool) -> DynamicScheme {
    SchemeTonalSpot::new(*hct, is_dark, None).scheme
}

fn print_color_scheme(name: &str, s: &Scheme) {
    println!("[color.{name}]");
    // Primary
    print_kv("primary", s.primary);
    print_kv("on_primary", s.on_primary);
    print_kv("primary_container", s.primary_container);
    print_kv("on_primary_container", s.on_primary_container);
    print_kv("inverse_primary", s.inverse_primary);
    // Secondary
    print_kv("secondary", s.secondary);
    print_kv("on_secondary", s.on_secondary);
    print_kv("secondary_container", s.secondary_container);
    print_kv("on_secondary_container", s.on_secondary_container);
    // Tertiary
    print_kv("tertiary", s.tertiary);
    print_kv("on_tertiary", s.on_tertiary);
    print_kv("tertiary_container", s.tertiary_container);
    print_kv("on_tertiary_container", s.on_tertiary_container);
    // Error
    print_kv("error", s.error);
    print_kv("on_error", s.on_error);
    print_kv("error_container", s.error_container);
    print_kv("on_error_container", s.on_error_container);
    // Background & surface
    print_kv("background", s.background);
    print_kv("on_background", s.on_background);
    print_kv("surface", s.surface);
    print_kv("on_surface", s.on_surface);
    print_kv("surface_variant", s.surface_variant);
    print_kv("on_surface_variant", s.on_surface_variant);
    print_kv("surface_tint", s.surface_tint);
    // Inverse surface
    print_kv("inverse_surface", s.inverse_surface);
    print_kv("inverse_on_surface", s.inverse_on_surface);
    // Surface tonal tiers
    print_kv("surface_dim", s.surface_dim);
    print_kv("surface_bright", s.surface_bright);
    print_kv("surface_container_lowest", s.surface_container_lowest);
    print_kv("surface_container_low", s.surface_container_low);
    print_kv("surface_container", s.surface_container);
    print_kv("surface_container_high", s.surface_container_high);
    print_kv("surface_container_highest", s.surface_container_highest);
    // Outlines
    print_kv("outline", s.outline);
    print_kv("outline_variant", s.outline_variant);
    print_kv("scrim", s.scrim);
}

fn print_fixed_colors(s: &Scheme) {
    println!("[color.fixed]");
    print_kv("primary_fixed", s.primary_fixed);
    print_kv("primary_fixed_dim", s.primary_fixed_dim);
    print_kv("on_primary_fixed", s.on_primary_fixed);
    print_kv("on_primary_fixed_variant", s.on_primary_fixed_variant);
    print_kv("secondary_fixed", s.secondary_fixed);
    print_kv("secondary_fixed_dim", s.secondary_fixed_dim);
    print_kv("on_secondary_fixed", s.on_secondary_fixed);
    print_kv("on_secondary_fixed_variant", s.on_secondary_fixed_variant);
    print_kv("tertiary_fixed", s.tertiary_fixed);
    print_kv("tertiary_fixed_dim", s.tertiary_fixed_dim);
    print_kv("on_tertiary_fixed", s.on_tertiary_fixed);
    print_kv("on_tertiary_fixed_variant", s.on_tertiary_fixed_variant);
}

fn print_kv(key: &str, value: Argb) {
    println!("{key:<26} = \"#{}\"", hex(value));
}

fn hex(c: Argb) -> String {
    format!("{:02X}{:02X}{:02X}", c.red, c.green, c.blue)
}
